name: Python Code Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run Black for code formatting
      run: |
        black --check .

    - name: Run Flake8 for linting
      run: |
        flake8 .

    - name: Run PEP 8 check
      run: |
        pip install pycodestyle
        pycodestyle .
