name: Python Checks and Auto-fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python 3.x environment
    - name: Setup Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pycodestyle

    # Run Black for auto-formatting
    - name: Auto-format with Black
      run: |
        black --check .
      continue-on-error: true

    # If Black has formatting suggestions, apply them
    - name: Apply auto-formatting with Black
      run: |
        black .
      if: failure()

    # Run Flake8 for linting
    - name: Lint with Flake8
      run: |
        flake8 .
      continue-on-error: true

    # Run PEP8 for style checks
    - name: Check style with PEP8 (pycodestyle)
      run: |
        pycodestyle --max-line-length=180 .
      continue-on-error: true

    # Add and commit changes made by Black
    - name: Commit changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Apply Black formatting" -a || echo "No changes to commit"
        git push
      continue-on-error: true

    # Manual intervention if linting failed
    - name: Manual Intervention Required
      if: failure()
      run: echo "Manual intervention required. Review the linting and formatting errors."

    # If all checks passed, indicate it's ready for review/merge
    - name: Ready for Review/Merge
      if: success()
      run: echo "All checks passed. Ready for review or merge."
