name: Python Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install black flake8

    - name: Run Black and Flake8
      run: |
        black . --check > check_log.txt 2>&1
        flake8 . --output-file=check_log.txt --append-output

    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: python-check-log
        path: check_log.txt
